services:
    app.admin.application:
        class: AppBundle\Admin\ApplicationAdmin
        arguments: [~, AppBundle\Entity\Application, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Application}

    app.admin.jew:
        class: AppBundle\Admin\JewAdmin
        arguments: [~, AppBundle\Entity\Jew, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Jew}
