services:
    app.admin.application:
        class: AppBundle\Admin\ApplicationAdmin
        arguments: [~, AppBundle\Entity\Application, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Application}
